# Generated by Django 3.0.3 on 2020-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigelistclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
